In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('rideshare_kaggle.csv');

In [38]:
df['price'].isnull().sum

<bound method Series.sum of 0         False
1         False
2         False
3         False
4         False
          ...
693065    False
693066    False
693067    False
693069    False
693070    False
Name: price, Length: 571027, dtype: bool>

In [8]:
df.dropna(subset=['price'], inplace=True)

In [9]:
df['price'].isnull().sum()

np.int64(0)

In [10]:
df.shape

(637976, 57)

In [11]:
columns_to_keep = [
    'cab_type', 'name', 'distance', 'surge_multiplier', 
    'source', 'destination', 'hour', 'day', 'month', 
    'temperature', 'short_summary', 'precipIntensity', 'price'
]

df = df[columns_to_keep]

In [12]:
df.shape

(637976, 13)

In [39]:
df.columns

Index(['cab_type', 'name', 'distance', 'surge_multiplier', 'source',
       'destination', 'hour', 'day', 'month', 'temperature', 'short_summary',
       'precipIntensity', 'price'],
      dtype='object')

In [14]:
df = df[df['price'] <= 45]
#remove outliers because >45$ prices are outliers

In [15]:
df.shape

(633011, 13)

In [17]:
 df.duplicated().sum()

np.int64(55885)

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.shape

(577126, 13)

In [21]:
df.dtypes

cab_type             object
name                 object
distance            float64
surge_multiplier    float64
source               object
destination          object
hour                  int64
day                   int64
month                 int64
temperature         float64
short_summary        object
precipIntensity     float64
price               float64
dtype: object

In [22]:
Q1 = df['distance'].quantile(0.25)
Q3 = df['distance'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['distance'] < lower) | (df['distance'] > upper)]

print(outliers)
print("Number of outliers:", len(outliers))

       cab_type      name  distance  surge_multiplier              source  \
516        Uber       WAV      7.46               1.0  Financial District
1977       Uber  UberPool      5.56               1.0  Financial District
1978       Uber       WAV      5.56               1.0  Financial District
1979       Uber     UberX      5.56               1.0  Financial District
1980       Uber     Black      5.56               1.0  Financial District
...         ...       ...       ...               ...                 ...
693004     Uber       WAV      7.36               1.0            Back Bay
693005     Uber  UberPool      7.36               1.0            Back Bay
693006     Uber     Black      7.36               1.0            Back Bay
693008     Uber     UberX      7.36               1.0            Back Bay
693009     Uber    UberXL      7.36               1.0            Back Bay

                    destination  hour  day  month  temperature  \
516     Northeastern University    20   14     12        45.35
1977          Boston University    23   16     12        41.29
1978          Boston University     3   17     12        40.45
1979          Boston University    16   16     12        42.42
1980          Boston University    11   17     12        34.87
...                         ...   ...  ...    ...          ...
693004                North End     5   30     11        33.78
693005                North End     5   30     11        33.78
693006                North End    18   13     12        32.67
693008                North End    18   13     12        32.67
693009                North End    18   13     12        32.67

          short_summary  precipIntensity  price
516      Partly Cloudy            0.0000   16.0
1977        Light Rain            0.0567   12.5
1978        Light Rain            0.0591   15.0
1979          Overcast            0.0036   15.0
1980          Overcast            0.0023   33.5
...                 ...              ...    ...
693004           Clear            0.0000   16.0
693005           Clear            0.0000   14.5
693006   Mostly Cloudy            0.0000   36.0
693008   Mostly Cloudy            0.0000   16.0
693009   Mostly Cloudy            0.0000   25.5

[6099 rows x 13 columns]
Number of outliers: 6099

In [23]:
df = df[(df['distance'] >= lower) & (df['distance'] <= upper)]

In [25]:
df.shape

(571027, 13)

In [26]:
categorical_cols = ['cab_type', 'name', 'source', 'destination', 'short_summary']
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [27]:
df_encoded.shape

(571027, 50)

In [28]:
df.shape

(571027, 13)

In [29]:
df_encoded.columns

Index(['distance', 'surge_multiplier', 'hour', 'day', 'month', 'temperature',
       'precipIntensity', 'price', 'cab_type_Uber', 'name_Black SUV',
       'name_Lux', 'name_Lux Black', 'name_Lux Black XL', 'name_Lyft',
       'name_Lyft XL', 'name_Shared', 'name_UberPool', 'name_UberX',
       'name_UberXL', 'name_WAV', 'source_Beacon Hill',
       'source_Boston University', 'source_Fenway',
       'source_Financial District', 'source_Haymarket Square',
       'source_North End', 'source_North Station',
       'source_Northeastern University', 'source_South Station',
       'source_Theatre District', 'source_West End', 'destination_Beacon Hill',
       'destination_Boston University', 'destination_Fenway',
       'destination_Financial District', 'destination_Haymarket Square',
       'destination_North End', 'destination_North Station',
       'destination_Northeastern University', 'destination_South Station',
       'destination_Theatre District', 'destination_West End',
       'short_summary_ Drizzle ', 'short_summary_ Foggy ',
       'short_summary_ Light Rain ', 'short_summary_ Mostly Cloudy ',
       'short_summary_ Overcast ', 'short_summary_ Partly Cloudy ',
       'short_summary_ Possible Drizzle ', 'short_summary_ Rain '],
      dtype='object')

In [30]:
from sklearn.preprocessing import MinMaxScaler

In [31]:
numeric_cols = ['distance', 'surge_multiplier', 'hour', 'day', 'month', 'temperature', 'precipIntensity']

scaler = MinMaxScaler()

In [32]:
df_encoded[numeric_cols] = scaler.fit_transform(df_encoded[numeric_cols])

In [33]:
df_encoded[numeric_cols]

,distance,surge_multiplier,hour,day,month,temperature,precipIntensity
0,0.078067,0.0,0.391304,0.517241,1.0,0.611590,0.000000
1,0.078067,0.0,0.086957,0.896552,0.0,0.643957,0.897719
2,0.078067,0.0,0.043478,0.931034,0.0,0.506917,0.000000
3,0.078067,0.0,0.173913,1.000000,0.0,0.403811,0.000000
4,0.078067,0.0,0.130435,0.965517,0.0,0.483686,0.000000
...,...,...,...,...,...,...,...
693065,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000
693066,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000
693067,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000
693069,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000
693070,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000

In [34]:
df_encoded

,distance,surge_multiplier,hour,day,month,temperature,precipIntensity,price,cab_type_Uber,name_Black SUV,...,destination_Theatre District,destination_West End,short_summary_ Drizzle,short_summary_ Foggy,short_summary_ Light Rain,short_summary_ Mostly Cloudy,short_summary_ Overcast,short_summary_ Partly Cloudy,short_summary_ Possible Drizzle,short_summary_ Rain
0,0.078067,0.0,0.391304,0.517241,1.0,0.611590,0.000000,5.0,False,False,...,False,False,False,False,False,True,False,False,False,False
1,0.078067,0.0,0.086957,0.896552,0.0,0.643957,0.897719,11.0,False,False,...,False,False,False,False,False,False,False,False,False,True
2,0.078067,0.0,0.043478,0.931034,0.0,0.506917,0.000000,7.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0.078067,0.0,0.173913,1.000000,0.0,0.403811,0.000000,26.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,0.078067,0.0,0.130435,0.965517,0.0,0.483686,0.000000,9.0,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693065,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000,9.5,True,False,...,False,False,False,False,False,False,False,True,False,False
693066,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000,13.0,True,False,...,False,False,False,False,False,False,False,True,False,False
693067,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000,9.5,True,False,...,False,False,False,False,False,False,False,True,False,False
693069,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000,27.0,True,True,...,False,False,False,False,False,False,False,True,False,False
693070,0.182156,0.0,1.000000,0.000000,1.0,0.473506,0.000000,10.0,True,False,...,False,False,False,False,False,False,False,True,False,False

In [35]:
df_encoded.to_csv("rideshare_encoded.csv", index=False)